### ISSUE TITLE
--environment-file errors 'String is not a file'

### ISSUE THREAD

**Issue by spuder** [jordansissel/pleaserun#123]
According to the help, you can pass in `--environment-file`

No matter how I provide that option, it gives error 'String is not a File'

    pleaserun --environment-file=/opt/solr/bin/solr.in.sh
    pleaserun --environment-file /opt/solr/bin/solr.in.sh
    pleaserun --environment-file='/opt/solr/bin/solr.in.sh'
    pleaserun --environment-file="/opt/solr/bin/solr.in.sh'
    pleaserun --environment-file "/opt/solr/bin/solr.in.sh"

I've verified that the file exists. 

```bash
root@solrft-ubuntu-1604:~# pleaserun --name 'derp' --user 'solr' --environment-file /opt/solr/bin/solr.in.sh /usr/lib/jvm/java-8-openjdk-amd64/bin/java -server start.jar
No platform selected. Autodetecting... {:platform=>"systemd", :version=>"229", :level=>:warn}
/var/lib/gems/2.3.0/gems/pleaserun-0.0.28/lib/pleaserun/configurable.rb:171:in `rescue in validate': Invalid value '"/opt/solr/bin/solr.in.sh"' for attribute 'environment_file' (String is not a File) (PleaseRun::Configurable::ValidationError)
	from /var/lib/gems/2.3.0/gems/pleaserun-0.0.28/lib/pleaserun/configurable.rb:169:in `validate'
	from /var/lib/gems/2.3.0/gems/pleaserun-0.0.28/lib/pleaserun/configurable.rb:164:in `value='
	from /var/lib/gems/2.3.0/gems/pleaserun-0.0.28/lib/pleaserun/configurable.rb:78:in `block in attribute'
	from /var/lib/gems/2.3.0/gems/pleaserun-0.0.28/lib/pleaserun/cli.rb:124:in `block in execute'
	from /var/lib/gems/2.3.0/gems/pleaserun-0.0.28/lib/pleaserun/cli.rb:114:in `each'
	from /var/lib/gems/2.3.0/gems/pleaserun-0.0.28/lib/pleaserun/cli.rb:114:in `execute'
	from /var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:63:in `run'
	from /var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
	from /var/lib/gems/2.3.0/gems/pleaserun-0.0.28/bin/pleaserun:6:in `<top (required)>'
	from /usr/local/bin/pleaserun:23:in `load'
	from /usr/local/bin/pleaserun:23:in `<main>'
```

**Comment by mailinglists35** [comment]
same here

**Comment by josegonzalez** [comment]
How are you installing pleaserun? There isn't a version `0.0.28` from what I can see.

**Comment by spuder** [comment]
With the 16.04 vagrant box. I think I installed just with the normal gems. I've since destroyed that vm. Here is what I get when I spin up a new vm

```
sudo apt-get update
sudo apt-get install ruby
...
vagrant@solrmd-ubuntu-1604:~$ sudo gem install pleaserun
sudo gem install pleaserun
Fetching: cabin-0.9.0.gem (100%)
Successfully installed cabin-0.9.0
Fetching: clamp-1.1.2.gem (100%)
Successfully installed clamp-1.1.2
Fetching: stud-0.0.22.gem (100%)
Successfully installed stud-0.0.22
Fetching: mustache-0.99.8.gem (100%)
Successfully installed mustache-0.99.8
Fetching: insist-1.0.0.gem (100%)
Successfully installed insist-1.0.0
Fetching: dotenv-2.2.0.gem (100%)
Successfully installed dotenv-2.2.0
Fetching: pleaserun-0.0.28.gem (100%)
Successfully installed pleaserun-0.0.28
Parsing documentation for cabin-0.9.0
Installing ri documentation for cabin-0.9.0
Parsing documentation for clamp-1.1.2
Installing ri documentation for clamp-1.1.2
Parsing documentation for stud-0.0.22
Installing ri documentation for stud-0.0.22
Parsing documentation for mustache-0.99.8
Installing ri documentation for mustache-0.99.8
Parsing documentation for insist-1.0.0
Installing ri documentation for insist-1.0.0
Parsing documentation for dotenv-2.2.0
Installing ri documentation for dotenv-2.2.0
Parsing documentation for pleaserun-0.0.28
Installing ri documentation for pleaserun-0.0.28
Done installing documentation for cabin, clamp, stud, mustache, insist, dotenv, pleaserun after 1 seconds
7 gems installed
```

**Comment by mailinglists35** [comment]
> How are you installing pleaserun?

I have installed like in instructions: "gem install pleaserun". Using centos 7.3

**Comment by jordansissel** [comment]
I ran into this problem today. I think it should be an easy fix.

**Comment by snarlistic** [comment]
Please see https://github.com/jordansissel/pleaserun/pull/129. This should fix this issue.
