### ISSUE TITLE
cannot load such file -- dotenv/parser

### ISSUE THREAD

**Issue by Apteryks** [jordansissel/pleaserun#154]
Hello!

I'm trying to package this for GNU Guix, and attempting to run "rspec" to run the test suite, I see:

```
starting phase `check'

An error occurred while loading ./spec/pleaserun/cli_spec.rb. - Did you mean?
                    rspec ./spec/pleaserun/detector_spec.rb

Failure/Error: require "dotenv/parser"

LoadError:
  cannot load such file -- dotenv/parser
# ./lib/pleaserun/platform/base.rb:1:in `<top (required)>'
# ./lib/pleaserun/cli.rb:8:in `<top (required)>'
# ./spec/pleaserun/cli_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/pleaserun/configurable_spec.rb. - Did you mean?
                    rspec ./spec/pleaserun/cli_spec.rb

Failure/Error: require "dotenv/parser"

LoadError:
  cannot load such file -- dotenv/parser
# ./lib/pleaserun/platform/base.rb:1:in `<top (required)>'
# ./spec/shared_examples.rb:1:in `<top (required)>'
# ./spec/testenv.rb:4:in `<top (required)>'
# ./spec/pleaserun/configurable_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/pleaserun/mustache_methods_spec.rb. - Did you mean?
                    rspec ./spec/pleaserun/detector_spec.rb

Failure/Error: require "dotenv/parser"

LoadError:
  cannot load such file -- dotenv/parser
# ./lib/pleaserun/platform/base.rb:1:in `<top (required)>'
# ./spec/shared_examples.rb:1:in `<top (required)>'
# ./spec/testenv.rb:4:in `<top (required)>'
# ./spec/pleaserun/mustache_methods_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/pleaserun/platform/base_spec.rb. - Did you mean?
                    rspec ./spec/pleaserun/platform/upstart_spec.rb
                    rspec ./spec/pleaserun/platform/systemd_spec.rb
                    rspec ./spec/pleaserun/platform/sysv_spec.rb

Failure/Error: require "dotenv/parser"

LoadError:
  cannot load such file -- dotenv/parser
# ./lib/pleaserun/platform/base.rb:1:in `<top (required)>'
# ./spec/shared_examples.rb:1:in `<top (required)>'
# ./spec/testenv.rb:4:in `<top (required)>'
# ./spec/pleaserun/platform/base_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/pleaserun/platform/launchd_spec.rb. - Did you mean?
                    rspec ./spec/pleaserun/platform/sysv_spec.rb
                    rspec ./spec/pleaserun/platform/base_spec.rb
                    rspec ./spec/pleaserun/platform/systemd_spec.rb

Failure/Error: require "dotenv/parser"

LoadError:
  cannot load such file -- dotenv/parser
# ./lib/pleaserun/platform/base.rb:1:in `<top (required)>'
# ./spec/shared_examples.rb:1:in `<top (required)>'
# ./spec/testenv.rb:4:in `<top (required)>'
# ./spec/pleaserun/platform/launchd_spec.rb:2:in `<top (required)>'

An error occurred while loading ./spec/pleaserun/platform/systemd_spec.rb. - Did you mean?
                    rspec ./spec/pleaserun/platform/sysv_spec.rb
                    rspec ./spec/pleaserun/platform/base_spec.rb
                    rspec ./spec/pleaserun/platform/upstart_spec.rb

Failure/Error: require "dotenv/parser"

LoadError:
  cannot load such file -- dotenv/parser
# ./lib/pleaserun/platform/base.rb:1:in `<top (required)>'
# ./spec/shared_examples.rb:1:in `<top (required)>'
# ./spec/testenv.rb:4:in `<top (required)>'
# ./spec/pleaserun/platform/systemd_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/pleaserun/platform/sysv_spec.rb. - Did you mean?
                    rspec ./spec/pleaserun/platform/systemd_spec.rb
                    rspec ./spec/pleaserun/platform/base_spec.rb
                    rspec ./spec/pleaserun/platform/upstart_spec.rb

Failure/Error: require "dotenv/parser"

LoadError:
  cannot load such file -- dotenv/parser
# ./lib/pleaserun/platform/base.rb:1:in `<top (required)>'
# ./spec/shared_examples.rb:1:in `<top (required)>'
# ./spec/testenv.rb:4:in `<top (required)>'
# ./spec/pleaserun/platform/sysv_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/pleaserun/platform/upstart_spec.rb. - Did you mean?
                    rspec ./spec/pleaserun/platform/base_spec.rb
                    rspec ./spec/pleaserun/platform/sysv_spec.rb
                    rspec ./spec/pleaserun/platform/systemd_spec.rb

Failure/Error: require "dotenv/parser"

LoadError:
  cannot load such file -- dotenv/parser
# ./lib/pleaserun/platform/base.rb:1:in `<top (required)>'
# ./spec/shared_examples.rb:1:in `<top (required)>'
# ./spec/testenv.rb:4:in `<top (required)>'
# ./spec/pleaserun/platform/upstart_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/pleaserun/user/base_spec.rb. - Did you mean?
                    rspec ./spec/pleaserun/platform/base_spec.rb
                    rspec ./spec/pleaserun/detector_spec.rb

Failure/Error: require "dotenv/parser"

LoadError:
  cannot load such file -- dotenv/parser
# ./lib/pleaserun/platform/base.rb:1:in `<top (required)>'
# ./spec/shared_examples.rb:1:in `<top (required)>'
# ./spec/testenv.rb:4:in `<top (required)>'
# ./spec/pleaserun/user/base_spec.rb:1:in `<top (required)>'


Finished in 0.00006 seconds (files took 0.62335 seconds to load)
0 examples, 0 failures, 9 errors occurred outside of examples

error: in phase 'check': uncaught exception:
%exception #<&invoke-error program: "rspec" arguments: () exit-status: 1 term-signal: #f stop-signal: #f> 
phase `check' failed after 0.9 seconds
```

The direct dependencies currently use are:
```
ruby-cabin@0.9.0 ruby-clamp@1.3.2 ruby-dotenv@2.8.1 ruby-insist@1.0.0 ruby-mustache@1.1.1
+ ruby-rspec@3.12.0 ruby-stud@0.0.23
```
And Ruby itself is at 2.7.4.

Thank you!

**Comment by Apteryks** [comment]
Hm, it's probably a packaging issue with `ruby-dotenv`; it doesn't seem to include the library files:

```
$ find /gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1 
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/lib
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/lib/ruby
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/lib/ruby/vendor_ruby
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/lib/ruby/vendor_ruby/build_info
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/lib/ruby/vendor_ruby/cache
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/lib/ruby/vendor_ruby/doc
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/lib/ruby/vendor_ruby/doc/dotenv-2.8.1
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/lib/ruby/vendor_ruby/doc/dotenv-2.8.1/ri
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/lib/ruby/vendor_ruby/doc/dotenv-2.8.1/ri/cache.ri
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/lib/ruby/vendor_ruby/extensions
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/lib/ruby/vendor_ruby/gems
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/lib/ruby/vendor_ruby/gems/dotenv-2.8.1
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/lib/ruby/vendor_ruby/specifications
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/lib/ruby/vendor_ruby/specifications/dotenv-2.8.1.gemspec
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/share
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/share/doc
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/share/doc/ruby-dotenv-2.8.1
/gnu/store/59q9xh6g879znk11qfbrnjfpkzbkiz0x-ruby-dotenv-2.8.1/share/doc/ruby-dotenv-2.8.1/LICENSE
```

**Comment by Apteryks** [comment]
It was indeed a dotenv packaging problem (the file list needed to be adjusted to use `find` instead of `git ls-files`, since there's no git metadata inside the build environment.

**Comment by jordansissel** [comment]
I’m glad you were able to get this sorted quickly! :)
