### ISSUE TITLE
running on ubuntu 1204 w/ ruby 1.8 fails

### ISSUE THREAD

**Issue by paulczar** [jordansissel/pleaserun#36]
```
root@derp:~# pleaserun -h
/usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': /var/lib/gems/1.8/gems/pleaserun-0.0.4/lib/pleaserun/mustache_methods.rb:25: undefined (?...) sequence: /(?<![\\])\$/ (SyntaxError)
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.8/gems/pleaserun-0.0.4/lib/pleaserun/platform/base.rb:3
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.8/gems/pleaserun-0.0.4/lib/pleaserun/cli.rb:7
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.8/gems/pleaserun-0.0.4/bin/pleaserun:5
	from /usr/local/bin/pleaserun:19:in `load'
	from /usr/local/bin/pleaserun:19
```

**Comment by jordansissel** [comment]
Just to update. Ruby 1.8.7 is still not supported by this project. I'm interested in having such support, but don't have the energy to commit to doing that myself right now.

**Comment by jordansissel** [comment]
I'd still like to support Ruby 1.8.7 for the nice folks who are stuck on ancient operating systems (RHEL/CentOS 5, Debian 4?), but at this time I don't have much energy to do this and further, it seems much of the ruby library author community has abandoned 1.8 so many of pleaserun's dependencies will fail under 1.8.
