### ISSUE TITLE
Could not find template file for 'init.d'

### ISSUE THREAD

**Issue by mbezjak** [jordansissel/pleaserun#39]
Went a little bit off script: https://github.com/jordansissel/pleaserun#generate-a-runner

    $ pleaserun -p sysv /tmp/redis/bin/redis-server

```
No name given, setting reasonable default {:name=>"redis-server", :level=>:warn}
/var/lib/gems/1.9.1/gems/pleaserun-0.0.4/lib/pleaserun/platform/base.rb:127:in `render_template': Could not find template file for 'init.d'. Tried all of these: ["/var/lib/gems/1.9.1/gems/pleaserun-0.0.4/lib/pleaserun/platform/../../../templates/sysv/default/init.d", "/var/lib/gems/1.9.1/gems/pleaserun-0.0.4/lib/pleaserun/platform/../../../templates/sysv/default/init.d", "/var/lib/gems/1.9.1/gems/pleaserun-0.0.4/lib/pleaserun/platform/../../../templates/sysv/init.d"] (PleaseRun::Platform::Base::InvalidTemplate)
        from /var/lib/gems/1.9.1/gems/pleaserun-0.0.4/lib/pleaserun/platform/sysv.rb:10:in `block in files'
        from /var/lib/gems/1.9.1/gems/pleaserun-0.0.4/lib/pleaserun/cli.rb:170:in `each'
        from /var/lib/gems/1.9.1/gems/pleaserun-0.0.4/lib/pleaserun/cli.rb:170:in `run_human'
        from /var/lib/gems/1.9.1/gems/pleaserun-0.0.4/lib/pleaserun/cli.rb:139:in `execute'
        from /var/lib/gems/1.9.1/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
        from /var/lib/gems/1.9.1/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
        from /var/lib/gems/1.9.1/gems/pleaserun-0.0.4/bin/pleaserun:7:in `<top (required)>'
        from /usr/local/bin/pleaserun:19:in `load'
        from /usr/local/bin/pleaserun:19:in `<main>'
```

    $ ruby -v
    ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux]

    $ cat /etc/issue
    Ubuntu 12.04.3 LTS

However, this does work with `-v lsb-3.1`.

    $ pleaserun -p sysv -v lsb-3.1 /tmp/redis/bin/redis-server

```
No name given, setting reasonable default {:name=>"redis-server", :level=>:warn}
Writing file {:destination=>"/tmp/studtmp-5e70ae83-c7de-4a7c-8200-5c904adba6da/etc/init.d/redis-server"}
Writing file {:destination=>"/tmp/studtmp-5e70ae83-c7de-4a7c-8200-5c904adba6da/etc/default/redis-server"}
```

**Comment by octomagon** [comment]
Found a bit more info CentOS 6.5

Feeding pleaserun -v lsb-4.0 causes the crash while...
```
[vagrant@localhost init.d]$ lsb_release                                                                                                                                                                                                       
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch

[vagrant@localhost init.d]$ pleaserun -p sysv -v lsb-4.0 /usr/share/kibana4/bin/kibana                                                                                                                                                        
No name given, setting reasonable default based on the executable {:name=>"kibana", :level=>:warn}
/usr/lib/ruby/gems/2.1.0/gems/pleaserun-0.0.9/lib/pleaserun/platform/base.rb:164:in `render_template': Could not find template file for 'init.sh'. Tried all of these: ["/usr/lib/ruby/gems/2.1.0/gems/pleaserun-0.0.9/lib/pleaserun/platform/
../../../templates/sysv/lsb-4.0/init.sh", "/usr/lib/ruby/gems/2.1.0/gems/pleaserun-0.0.9/lib/pleaserun/platform/../../../templates/sysv/default/init.sh", "/usr/lib/ruby/gems/2.1.0/gems/pleaserun-0.0.9/lib/pleaserun/platform/../../../templ
ates/sysv/init.sh"] (PleaseRun::Platform::Base::InvalidTemplate)
        from /usr/lib/ruby/gems/2.1.0/gems/pleaserun-0.0.9/lib/pleaserun/platform/sysv.rb:10:in `block in files'
        from /usr/lib/ruby/gems/2.1.0/gems/pleaserun-0.0.9/lib/pleaserun/installer.rb:18:in `each'
        from /usr/lib/ruby/gems/2.1.0/gems/pleaserun-0.0.9/lib/pleaserun/installer.rb:18:in `install_files'
        from /usr/lib/ruby/gems/2.1.0/gems/pleaserun-0.0.9/lib/pleaserun/cli.rb:177:in `run_human'
        from /usr/lib/ruby/gems/2.1.0/gems/pleaserun-0.0.9/lib/pleaserun/cli.rb:128:in `execute'
        from /usr/lib/ruby/gems/2.1.0/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
        from /usr/lib/ruby/gems/2.1.0/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
        from /usr/lib/ruby/gems/2.1.0/gems/pleaserun-0.0.9/bin/pleaserun:6:in `<top (required)>'
        from /usr/bin/pleaserun:23:in `load'
        from /usr/bin/pleaserun:23:in `<main>'
```

-v lsb-3.1 does not.

```
[vagrant@localhost init.d]$ pleaserun -p sysv -v lsb-3.1 /usr/share/kibana4/bin/kibana                                                                                                                                                        
No name given, setting reasonable default based on the executable {:name=>"kibana", :level=>:warn}
Writing file {:destination=>"/tmp/studtmp-4183a3df7715b5a39af3801581b46e9bb70506ff1907ae2ddb0025aee70b/etc/init.d/kibana"}
Writing file {:destination=>"/tmp/studtmp-4183a3df7715b5a39af3801581b46e9bb70506ff1907ae2ddb0025aee70b/etc/default/kibana"}
```

Though the LSB Version is wrong, it still gave me perfectly sexy init scripts.
```
[vagrant@localhost init.d]$ sudo pleaserun -p sysv -v lsb-3.1 --install /usr/share/kibana4/bin/kibana                                                                                                                                         
No name given, setting reasonable default based on the executable {:name=>"kibana", :level=>:warn}
Writing file {:destination=>"/etc/init.d/kibana"}
Writing file {:destination=>"/etc/default/kibana"}

[vagrant@localhost init.d]$ sudo service kibana start                                                                                                                                                                                       
kibana started
[vagrant@localhost init.d]$ sudo lsof -i | grep node                                                                                                                                                                                          
node      13826          root   10u  IPv4  53898      0t0  TCP localhost:52434->localhost:wap-wsp (ESTABLISHED)
node      13826          root   11u  IPv4  53901      0t0  TCP *:esmagent (LISTEN)
[vagrant@localhost init.d]$ sudo service kibana stop                                                                                                                                                                                          
kibana stopped.
[vagrant@localhost init.d]$ sudo lsof -i | grep node                                                                                                                                                                                          
[vagrant@localhost init.d]$
```

**Comment by jordansissel** [comment]
lsb 4.0 init is not supported at this time, though I would accept patches adding support for it. For CentOS 6, I *highly* recommend you use Upstart, not init scripts. Upstart is what pleaserun defaults to when CentOS 6 is detected, but the choice is up to you :)

**Comment by octomagon** [comment]
This may be a silly newb question :) but... the elasticsearch & logstash RPMs seem to install via init on EL6 instead of upstart.  Is that just for wider compatibility?

My end goal is to create an RPM for Kibana to use temporarily until an official one comes out.  I thought it  would be better to use what the rest of the ELK stack uses for consistency and user-friendliness.  Does that make sense?

**Comment by jordansissel** [comment]
>  Is that just for wider compatibility?

Yes :)

I can go into more detail -

@octomagon this is because we only build 1 package of each type (rpm, deb), so you get the same exact package on all rpm platforms (suse, centos 5-7, rhel 5-7, fedora, etc). I'd love to improve this, but unfortunately there are so many reasons this is difficult, roughly categorized as technical or personal.

1) Personal: Many users are violently against systemd, so I am not yet willing to burden myself with that violence. So I don't want to ship systemd services yet with logstash.
2) Personal: Many users don't know that upstart/systemd/etc are available (for many years, now). Lack of knowledge is totally OK! I stick with shipping sysv init scripts because it's what most folks seem to expect. I've had problems shipping up upstart configs where users don't even know upstart exists (or is default!) on their platform.
3) Technical: We only have one package per type, right now. This can change, but until it does, we can't ship 1 package with all 3 variants (sysv, upstart, systemd) because Bad Things Happen when we do that.
4) Technical: Related to 3. We could have a post-install step that determines the platform and activates the correct service (systemd on centos 7, for example), but this leads us down the route inviting user confusion (2) and user violence (1).
5) Technical: Alternate solution to 4, related to 3. We could ship 1 package per platform-version (RHEL 5, RHEL 6, RHEL 6, Fedora 20, Fedora 21, etc), but this isn't something we do right now. It has the same problems as 4 (user confusion and violence)

So this was a long way to answer your question. Hopefully it helps inform! :)

**Comment by octomagon** [comment]
Thanks for the excellent answer!!!
That was super helpful :)

**Comment by jordansissel** [comment]
@octomagon my hope for fpm's pleaserun support is to "do the best thing" (best == relative to platform), so that:

```
fpm -s pleaserun -t rpm some/program
```

The above would build an rpm including all necessary platform support to run 'some/program' as a service/daemon/task/whatever-we-call-it. Then `yum install mypackage` would detect the platform and install the most-correct service config (sysv, systemd, upstart, etc!).

Related: https://github.com/jordansissel/fpm/issues/856

**Comment by octomagon** [comment]
God, that looks sexy...
Now I have to learn Ruby :)

**Comment by jakerobinson** [comment]
@jordansissel Hopefully save you some time... this is the same root cause as #24. The symlink for `default` to `lsb-3.1` is not getting created when you do a `gem install`.

**Comment by jordansissel** [comment]
@jakerobinson ooh good catch. I didn't really like the symlink "default" stuff anyway. I'll figure a better way about it that's more cross platform soon

**Comment by spuder** [comment]
It looks like this isn't unique to centos 6. I get the same crash on both ubuntu 14.04 and Mac OSX systems. 

```
NV\sowen@kafka-manager:/opt$ pleaserun -p sysv /opt/kafka-manager/bin/kafka-manager -Dconfig.file=/opt/kafka/config/application.conf -Dhttp.port=8080
No name given, setting reasonable default based on the executable {:name=>"kafka-manager", :level=>:warn}
/var/lib/gems/1.9.1/gems/pleaserun-0.0.11/lib/pleaserun/platform/base.rb:168:in `render_template': Could not find template file for 'init.sh'. Tried all of these: ["/var/lib/gems/1.9.1/gems/pleaserun-0.0.11/lib/pleaserun/platform/../../../templates/sysv/default/init.sh", "/var/lib/gems/1.9.1/gems/pleaserun-0.0.11/lib/pleaserun/platform/../../../templates/sysv/default/init.sh", "/var/lib/gems/1.9.1/gems/pleaserun-0.0.11/lib/pleaserun/platform/../../../templates/sysv/init.sh"] (PleaseRun::Platform::Base::InvalidTemplate)
	from /var/lib/gems/1.9.1/gems/pleaserun-0.0.11/lib/pleaserun/platform/sysv.rb:10:in `block in files'
	from /var/lib/gems/1.9.1/gems/pleaserun-0.0.11/lib/pleaserun/installer.rb:18:in `each'
	from /var/lib/gems/1.9.1/gems/pleaserun-0.0.11/lib/pleaserun/installer.rb:18:in `install_files'
	from /var/lib/gems/1.9.1/gems/pleaserun-0.0.11/lib/pleaserun/cli.rb:177:in `run_human'
	from /var/lib/gems/1.9.1/gems/pleaserun-0.0.11/lib/pleaserun/cli.rb:128:in `execute'
	from /var/lib/gems/1.9.1/gems/clamp-0.6.4/lib/clamp/command.rb:67:in `run'
	from /var/lib/gems/1.9.1/gems/clamp-0.6.4/lib/clamp/command.rb:132:in `run'
	from /var/lib/gems/1.9.1/gems/pleaserun-0.0.11/bin/pleaserun:6:in `<top (required)>'
	from /usr/local/bin/pleaserun:23:in `load'
	from /usr/local/bin/pleaserun:23:in `<main>'
```

It looks like if you use `-p sysv` you *must* also use `-v lsb-3.1`.

**Comment by jordansissel** [comment]
@spuder yes, for now version is required and the error message you get without it is... bad.

**Comment by spuder** [comment]
Relevant, Ubuntu is switching to systemd

https://lists.ubuntu.com/archives/ubuntu-devel-announce/2015-March/001130.html

**Comment by jordansissel** [comment]
@spuder yep! Once the next ubuntu is released, we can add a mapping in the platform detector to make newer ubuntu default to systemd.

**Comment by jordansissel** [comment]
This should work now. I just tested and it seem sok.

**Comment by jordansissel** [comment]
Definitely file a new ticket if you have other issues :)
