### ISSUE TITLE
Error 'UnknownSystem'

### ISSUE THREAD

**Issue by igoreliasm** [jordansissel/pleaserun#80]
Hello. I'm using CentOS6.5 and ruby2.2.
I'm having this error:
```
pleaserun --install ./bin/elasticsearch
/usr/local/lib/ruby/gems/2.2.0/gems/pleaserun-0.0.16/lib/pleaserun/detector.rb:50:in `detect': true  (PleaseRun::Detector::UnknownSystem)
	from /usr/local/lib/ruby/gems/2.2.0/gems/pleaserun-0.0.16/lib/pleaserun/cli.rb:140:in `setup_defaults'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pleaserun-0.0.16/lib/pleaserun/cli.rb:107:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pleaserun-0.0.16/bin/pleaserun:6:in `<top (required)>'
	from /usr/local/bin/pleaserun:23:in `load'
	from /usr/local/bin/pleaserun:23:in `<main>'
```

**Comment by neoice** [comment]
I'm on CentOS 6.6 and Ruby2.1 and get a similar, but easily resolved, error: `Could not detect because neither ohai nor facter libraries are found (PleaseRun::Detector::UnknownSystem)`

simply `gem install` and move onward. maybe your `pleaserun` is outdated and isn't showing you the helpful error message? or maybe you've discovered some cool way of breaking pleaserun :P

```
/usr/ruby/2.1.2/lib/ruby/gems/2.1.0/gems/pleaserun-0.0.16/lib/pleaserun/detector.rb:45:in `rescue in rescue in detect': Could not detect because neither ohai nor facter libraries are found (PleaseRun::Detector::UnknownSystem)
	from /usr/ruby/2.1.2/lib/ruby/gems/2.1.0/gems/pleaserun-0.0.16/lib/pleaserun/detector.rb:42:in `rescue in detect'
	from /usr/ruby/2.1.2/lib/ruby/gems/2.1.0/gems/pleaserun-0.0.16/lib/pleaserun/detector.rb:38:in `detect'
	from /usr/ruby/2.1.2/lib/ruby/gems/2.1.0/gems/pleaserun-0.0.16/lib/pleaserun/cli.rb:140:in `setup_defaults'
	from /usr/ruby/2.1.2/lib/ruby/gems/2.1.0/gems/pleaserun-0.0.16/lib/pleaserun/cli.rb:107:in `execute'
	from /usr/ruby/2.1.2/lib/ruby/gems/2.1.0/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /usr/ruby/2.1.2/lib/ruby/gems/2.1.0/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
	from /usr/ruby/2.1.2/lib/ruby/gems/2.1.0/gems/pleaserun-0.0.16/bin/pleaserun:6:in `<top (required)>'
	from /usr/ruby/2.1.2/bin/pleaserun:23:in `load'
	from /usr/ruby/2.1.2/bin/pleaserun:23:in `<main>'
```

**Comment by jordansissel** [comment]
The platform detector has been rewritten to not infer the platform from the operating system, so I think this is fixed now.
