### ISSUE TITLE
`-p upstart` seems requires version?

### ISSUE THREAD

**Issue by solarce** [jordansissel/pleaserun#83]
It seems like `-p upstart` requires a version to be set?

When I run try without one (I guess assuming it would default to some version), I get 

```
~/code pleaserun -p upstart /usr/bin/af
No name given, setting reasonable default based on the executable {:name=>"af", :level=>:warn}
/home/solarce/.gem/ruby/2.2.0/gems/pleaserun-0.0.16/lib/pleaserun/platform/base.rb:168:in `render_template': Could not find template file for 'init.conf'. Tried all of these: ["/home/solarce/.gem/ruby/2.2.0/gems/pleaserun-0.0.16/lib/pleaserun/platform/../../../templates/upstart/default/init.conf", "/home/solarce/.gem/ruby/2.2.0/gems/pleaserun-0.0.16/lib/pleaserun/platform/../../../templates/upstart/default/init.conf", "/home/solarce/.gem/ruby/2.2.0/gems/pleaserun-0.0.16/lib/pleaserun/platform/../../../templates/upstart/init.conf"] (PleaseRun::Platform::Base::InvalidTemplate)
        from /home/solarce/.gem/ruby/2.2.0/gems/pleaserun-0.0.16/lib/pleaserun/platform/upstart.rb:9:in `block in files'
        from /home/solarce/.gem/ruby/2.2.0/gems/pleaserun-0.0.16/lib/pleaserun/installer.rb:18:in `each'
        from /home/solarce/.gem/ruby/2.2.0/gems/pleaserun-0.0.16/lib/pleaserun/installer.rb:18:in `install_files'
        from /home/solarce/.gem/ruby/2.2.0/gems/pleaserun-0.0.16/lib/pleaserun/cli.rb:177:in `run_human'
        from /home/solarce/.gem/ruby/2.2.0/gems/pleaserun-0.0.16/lib/pleaserun/cli.rb:128:in `execute'
        from /usr/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
        from /usr/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
        from /home/solarce/.gem/ruby/2.2.0/gems/pleaserun-0.0.16/bin/pleaserun:6:in `<top (required)>'
        from /home/solarce/.gem/ruby/2.2.0/bin/pleaserun:23:in `load'
        from /home/solarce/.gem/ruby/2.2.0/bin/pleaserun:23:in `<main>'
```

But if I use a version it's happy

```
~/code pleaserun -p upstart -v 1.5 /usr/bin/af
No name given, setting reasonable default based on the executable {:name=>"af", :level=>:warn}
Writing file {:destination=>"/tmp/studtmp-80f484b4d889d2f6416c833632734dca626cbf197aad30f42c592728cb88/etc/init/af.conf"}
```

**Comment by jordansissel** [comment]
Yeah, version is required. The error you get is a kind of relic from The Before Time when I had some other random ideas like default versions, etc. I'll fix that. <3

**Comment by jordansissel** [comment]
I think this is fixed now. The default "version" is now "default" and should work in most cases for the platforms available.
